// src/components/NavBar.vue
<template>
  <header class="header">
    <nav class="navbar">
      <a class="logo" href="/">
        <img :src="logo" alt="ShindoClient Logo" />
      </a>

      <button class="hamburger" :class="{active: menu}" @click="menu = !menu" aria-label="Menu">
        <span/><span/><span/>
      </button>

      <ul class="nav-links" :class="{ active: menu }">
        <li><RouterLink :to="{ path: '/', hash: '#hero' }"     @click="close">Home</RouterLink></li>
        <li><RouterLink :to="{ path: '/', hash: '#features' }" @click="close">Features</RouterLink></li>
        <li><RouterLink :to="{ path: '/', hash: '#about' }"    @click="close">About</RouterLink></li>
        <li><RouterLink :to="{ path: '/', hash: '#gallery' }"  @click="close">Gallery</RouterLink></li>
        <li><RouterLink :to="{ path: '/', hash: '#faq' }"      @click="close">FAQ</RouterLink></li>
        <li><RouterLink to="/download" @click="close">Download</RouterLink></li>
        <li><RouterLink to="/discord"  @click="close">Discord</RouterLink></li>
      </ul>

    </nav>
  </header>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import logo from '@/assets/logo.png'

const router = useRouter()
const route  = useRoute()
const menu = ref(false)
const close = () => (menu.value = false)

async function go(hash: string) {
  const onHome = route.path === '/'
  close()
  if (!onHome) {
    await router.push({ path: '/', hash })
    await scrollToHash(hash)
  } else {
    await scrollToHash(hash)
    router.replace({ hash })
  }
}
</script>

<style scoped>
.header{
  position:fixed; inset-inline:0; top:16px; z-index:1000;
  display:flex; justify-content:center;
}
.navbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  max-width: 1200px;
  margin: 0 auto;
  width: 100%;
  height: auto;
  background-color: rgba(41, 41, 56, 0.3);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 50px;
  overflow: visible;
  box-shadow: 0 0px 12px rgba(0, 0, 0, 0.2);
  transition: box-shadow 0.2s;
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  padding: 1rem 1.5rem;
}
.navbar:hover {
  box-shadow: 0 0px 20px rgba(0, 0, 0, 0.4);
}

.logo {
  color: var(--secondary);
  font-size: 1.5rem;
  font-weight: 700;
  height: 40px;
  display: flex;
  align-items: center;
}

.logo img {
  height: 40px;
  width: auto;
}

.nav-links {
  display: flex;
  gap: 1rem;
  list-style: none;
}

.nav-links li a,
.nav-links li .nav-btn{
  color: rgba(255,255,255,.7);
  text-decoration: none;
  font-weight: 500;
  padding: 0.5rem 0.75rem;
  transition: all 0.2s ease;
  display: flex; align-items: center; justify-content: center;
  background: none; border: 0; cursor: pointer; font: inherit;
}

.nav-links li a:hover,
.nav-links li .nav-btn:hover{
  color: #fff;
  transform: translateY(-1px);
}

/* no @media (max-width: 700px), onde você estiliza '.nav-links li a', duplique para '.nav-btn' também: */

.hamburger {
  display: none;
  cursor: pointer;
  padding: 10px;
  background: transparent;
  border: none;
  z-index: 2000;
}

.hamburger span {
  display: block;
  width: 30px;
  height: 2px;
  margin: 6px 0;
  background: var(--secondary);
  transition: transform 0.4s ease, opacity 0.3s ease;
}

.hamburger.active span:nth-child(1) {
  transform: rotate(45deg) translate(5px, 5px);
}

.hamburger.active span:nth-child(2) {
  opacity: 0;
}

.hamburger.active span:nth-child(3) {
  transform: rotate(-45deg) translate(7px, -7px);
}

@media (max-width: 700px) {

  .hamburger {
    display: block;
  }

  .navbar {
    flex-direction: column;
    align-items: stretch;
    overflow: hidden;
    transition: all 0.4s cubic-bezier(0.645, 0.045, 0.355, 1);
    padding-bottom: 1rem;
  }

  .navbar {
    position: relative;
  }

  .navbar::before {
    content: '';
    position: absolute;
    top: 1rem;
    left: 1.5rem;
    right: 1.5rem;
    height: 40px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    pointer-events: none;
  }

  .logo {
    position: relative;
    z-index: 10;
  }

  .hamburger {
    position: absolute;
    top: 1rem;
    right: 1.5rem;
    z-index: 10;
    margin: 0;
    padding: 5px;
  }

  .nav-links li a,
  .nav-links li .nav-btn{
    padding: 0.8rem 1rem;
    font-size: 1.1rem;
    border-radius: 25px;
    width: 100%;
    text-align: center;
    background-color: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    margin: 0.25rem 0;
  }
  .nav-links li a:hover,
  .nav-links li .nav-btn:hover{
    background-color: rgba(255, 255, 255, 0.166);
    border-color: rgba(255, 255, 255, 0.253);
    transform: translateY(-2px);
  }

  .nav-links {
    flex-direction: column;
    gap: 0.5rem;
    width: 100%;
    margin-top: 0rem;
    max-height: 0;
    opacity: 0;
    overflow: hidden;
    transition: all 0.6s cubic-bezier(0.645, 0.045, 0.355, 1);
  }

  /* Active state - expand the nav links */
  .nav-links.active {
    max-height: 400px;
    opacity: 1;
    margin-top: 1.5rem;
    padding-bottom: 1rem;
  }

  /* Navigation Items Animation */
  .nav-links li {
    opacity: 0;
    transform: translateY(-10px);
    transition: opacity 0.3s ease, transform 0.4s ease;
  }

  /* Active State Styles */
  .nav-links.active li {
    opacity: 1;
    transform: translateY(0);
  }

  /* Staggered Animation Delays */
  .nav-links.active li:nth-child(1) { transition-delay: 0.1s; }
  .nav-links.active li:nth-child(2) { transition-delay: 0.2s; }
  .nav-links.active li:nth-child(3) { transition-delay: 0.3s; }
  .nav-links.active li:nth-child(4) { transition-delay: 0.25s; }
  .nav-links.active li:nth-child(5) { transition-delay: 0.3s; }
  .nav-links.active li:nth-child(6) { transition-delay: 0.35s; }

  /* Mobile Menu Items */
  .nav-links li {
    width: 100%;
  }
}
</style>

// src/lib/components/NavBar.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import { siteConfig } from '$lib/site-config'
  import { scrollToHash } from '$lib/scroll'
  import type { ClientMeta } from '$lib/api'
  import { onMount } from 'svelte'

  let { clientMeta }: { clientMeta: ClientMeta } = $props()

  const primaryLinks = [
    { label: 'Overview', hash: '#hero' },
    { label: 'Features', hash: '#features' },
    { label: 'Showcase', hash: '#showcase' },
    { label: 'Support', hash: '#support' },
    { label: 'Roadmap', hash: '#roadmap' },
    { label: 'FAQ', hash: '#faq' }
  ] as const

  let menu = $state(false)
  let isScrolled = $state(false)

  const discordHref = $derived(clientMeta?.discord || siteConfig.discordUrl)
  const versionLabel = $derived(clientMeta?.latestversion ? `Version ${clientMeta.latestversion}` : null)

  function close() {
    menu = false
  }

  function toggle() {
    menu = !menu
  }

  async function navigate(hash: string) {
    close()

    if (page.url.pathname !== '/') {
      await goto(`/${hash}`)
    }

    await scrollToHash(hash)
    history.replaceState({}, '', hash)
  }

  onMount(() => {
    const handleScroll = () => {
      isScrolled = window.scrollY > 20
    }

    handleScroll()
    window.addEventListener('scroll', handleScroll, { passive: true })

    return () => {
      window.removeEventListener('scroll', handleScroll)
    }
  })
</script>

<header class:scrolled={isScrolled} class="site-header fixed inset-x-0 top-0 z-50 flex justify-center px-4 pt-5 transition-all duration-500 md:pt-6">
  <nav class:nav-scrolled={isScrolled} class="glass-panel glass-panel--static flex w-full max-w-[1120px] items-center justify-between gap-6 rounded-3xl border border-white/10 bg-gradient-to-r from-surface-panel/85 via-surface-panel-2/85 to-surface/85 px-5 py-3 shadow-[0_25px_80px_-50px_rgba(127,95,255,0.55)] backdrop-blur-2xl transition-all duration-500 hover:border-accent-500/35 md:px-7">
    <a class="flex items-center gap-3 text-sm font-semibold tracking-wide text-white/80 transition-all duration-300 hover:scale-105 hover:text-white" href="/">
      <img alt="ShindoClient logo" class="h-9 w-9 rounded-xl border border-accent-500/30 bg-white/10 p-1.5 shadow-[0_10px_35px_-20px_rgba(127,95,255,0.7)] transition-transform duration-300 hover:rotate-6" src="/logo.png" />
      <div class="flex flex-col leading-tight">
        <span class="font-display text-base uppercase tracking-[0.3em] text-white/70 transition-colors duration-300">ShindoClient</span>
        {#if versionLabel}
          <span class="text-[10px] font-medium uppercase tracking-[0.35em] text-white/40">
            {versionLabel}
          </span>
        {/if}
      </div>
    </a>

    <div class="hidden items-center gap-1 text-sm font-medium text-white/70 md:flex">
      {#each primaryLinks as item}
        <button class="nav-link rounded-full px-4 py-2 transition-all duration-300 hover:bg-accent-500/10 hover:text-white hover:shadow-[0_10px_40px_-20px_rgba(127,95,255,0.6)]" type="button" onclick={() => navigate(item.hash)}>
          {item.label}
        </button>
      {/each}
      <a class="button-ghost ml-1 border-accent-500/25 bg-accent-500/10 text-xs uppercase tracking-widest hover:border-accent-500/40 hover:bg-accent-500/20" href="/Download">
        Download
      </a>
      <a class="button-primary bg-gradient-to-r from-accent-500 via-accent-600 to-accent-900 text-xs uppercase tracking-widest shadow-[0_20px_60px_-35px_rgba(127,95,255,0.75)]" href="/Discord">
        Discord
      </a>
    </div>

    <button aria-label="Toggle navigation" class="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/15 bg-white/10 text-white/80 transition hover:border-white/30 hover:text-white md:hidden" type="button" onclick={toggle}>
      {#if !menu}
        <svg class="h-6 w-6" fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.8" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path d="M5 7h14"></path>
          <path d="M5 12h14"></path>
          <path d="M5 17h14"></path>
        </svg>
      {:else}
        <svg class="h-6 w-6" fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.8" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path d="M6 6l12 12"></path>
          <path d="M6 18L18 6"></path>
        </svg>
      {/if}
    </button>
  </nav>

  {#if menu}
    <div class="absolute top-[88px] w-full max-w-[1120px] rounded-3xl border border-white/10 bg-gradient-to-br from-surface-panel/92 via-surface-panel-2/92 to-surface/95 p-4 shadow-xl shadow-black/40 backdrop-blur-2xl md:hidden">
      <div class="flex flex-col gap-2 text-sm font-medium text-white/70">
        {#each primaryLinks as item}
          <button class="rounded-2xl bg-white/5 px-4 py-3 text-left transition hover:bg-accent-500/15 hover:text-white" type="button" onclick={() => navigate(item.hash)}>
            {item.label}
          </button>
        {/each}
      </div>
      <div class="mt-4 grid gap-2">
        <a class="button-ghost w-full justify-center border-accent-500/25 bg-accent-500/10 text-xs uppercase tracking-[0.25em] hover:border-accent-500/40 hover:bg-accent-500/20" href="/download" onclick={close}>
          Download
        </a>
        <a class="button-primary w-full justify-center bg-gradient-to-r from-accent-500 via-accent-600 to-accent-900 text-xs uppercase tracking-[0.25em]" href="/discord" onclick={close}>
          Discord
        </a>
      </div>
    </div>
  {/if}
</header>

<style>
  .site-header {
    transform: translateY(0);
    transition:
      transform 0.5s cubic-bezier(0.4, 0, 0.2, 1),
      padding-top 0.5s cubic-bezier(0.4, 0, 0.2, 1);
  }

  .site-header.scrolled {
    padding-top: 0.75rem;
  }

  .nav-scrolled {
    box-shadow: 0 8px 32px -8px rgba(10, 18, 46, 0.6) !important;
    border-color: rgba(127, 95, 255, 0.35) !important;
    background: linear-gradient(90deg, rgba(15, 18, 43, 0.9), rgba(12, 15, 36, 0.9), rgba(5, 6, 17, 0.92)) !important;
  }

  button[type='button'] {
    position: relative;
  }

  button[type='button']::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 50%;
    width: 0;
    height: 2px;
    background: linear-gradient(90deg, transparent, rgba(127, 95, 255, 0.8), transparent);
    transform: translateX(-50%);
    transition: width 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  }

  button[type='button']:hover::after {
    width: 60%;
  }
</style>
